Name:           ros-kinetic-rospack
Version:        2.3.3
Release:        0%{?dist}
Summary:        ROS rospack package
Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rospack
Source0:        %{name}-%{version}.tar.gz
Source1001:     %{name}.manifest
BuildRequires:  cmake
BuildRequires:  gcc-c++
BuildRequires:  boost-devel
BuildRequires:  gtest-devel
BuildRequires:  pkg-config
BuildRequires:  python-coverage
BuildRequires:  python-devel
BuildRequires:  tinyxml-devel
BuildRequires:  ros-kinetic-catkin >= 0.5.68
BuildRequires:  ros-kinetic-cmake-modules
Requires:       boost-devel
Requires:       gtest-devel
Requires:       pkg-config
Requires:       python-catkin_pkg
Requires:       python-devel
Requires:       python-rosdep
Requires:       tinyxml-devel

%define         install_path /opt/ros/kinetic
%define         src_name rospack

%description
ROS Package Tool

%prep
%setup -q
cp %{SOURCE1001} .

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/usr/setup.sh" ]; then . "/usr/setup.sh"; fi
mkdir build && cd build
cmake .. \
        -DCMAKE_INSTALL_PREFIX="%{install_path}" \
        -DCMAKE_PREFIX_PATH="%{install_path}" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" 

make %{?_smp_mflags}

#        -DCMAKE_INSTALL_PREFIX="%{install_path}" \
#        -DCMAKE_PREFIX_PATH="%{install_path}" \
%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/usr/setup.sh" ]; then . "/usr/setup.sh"; fi
pushd build
make install DESTDIR=%{buildroot}
popd

%files -f build/install_manifest.txt
%manifest %{name}.manifest
%defattr(-,root,root)

%changelog
* Thu Mar 30 2017 Zhang Xingtao <xingtao.zhang@yahoo.com> - 2.2.8
* Fri May 09 2014 Dirk Thomas <dthomas@osrfoundation.org> - 2.1.21-0
- Autogenerated by Bloom

